# Site settings
title: 离青
description: > #
  我认为的光芒 <br />
  是用阴暗点燃的光芒 <br />
  我认为的时刻 <br />
  是缺席所有重要事件的时刻 <br />
  我认为的死亡 <br />
  是实则悬崖勒马却无法被看到的死亡 <br />
  我认为的活着 <br />
  是分外踏实的活着 <br />
  像一个画家 笔尖落下的点<br />
  那个点还在 他就还活着

baseurl: "https://li-qing.github.io/"
url: "https://li-qing.github.io/"
email: lshhch@gmail.com
github_username: li-qing

# Build settings
markdown: kramdown
#markdown: redcarpet
#highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
paginate: 5
